### PR TITLE
Update documents

### PR DESCRIPTION
**Pull request by k-takata**
* Update OS name.
* Update Cygwin build command.

### CODE REVIEW

**Comment by Shougo** [comment]
Can you fix the conflicts?

**Comment by k-takata** [comment]
https://github.com/Shougo/vimproc.vim/blob/e3de9881267c251545653c81c8d7417a21254410/doc/vimproc.txt#L98-L99

How about this?

> If you want to use BSD make, use the platform specific makefile:

**Comment by Shougo** [comment]
> If you want to use BSD make, use the platform specific makefile:

You can change the description.

**Comment by Shougo** [comment]
Merged.

**Pull request merged**
