### PR TITLE
win32: Update build system

### PR DESCRIPTION
**Pull request by k-takata**
* Stop using Win32.mak.
  Using it is outdated. No need to set SDK_INCLUDE_DIR anymore.
* Update how to detect the target platform.
* Change fileformat to unix for consistency.
* Change how to update vimproc.dll.
  Simplify the batch files.
* Clean only current architecture.
  Don't clean x86 when build x64 and vice versa.

### CODE REVIEW

**Comment by Shougo** [comment]
It can be merged?

Note: Appveyor failed.

**Comment by k-takata** [comment]
Please wait until AppVeyor is fixed.

**Comment by k-takata** [comment]
Ok, passed.
However, it is very strange that the [previous commit](https://github.com/Shougo/vimproc.vim/pull/300/commits/d59e74453b696ddfeb5aa38d04dccab8c26b7c5e) failed. It should not fail, and it works fine in my local environment.

**Comment by Shougo** [comment]
Thanks. Merged.

**Pull request merged**
