### PR TITLE
Use new data format

### PR DESCRIPTION
**Pull request by k-takata**
*This PR is work in progress.*

Each value consists of DataSize, Data, and EOV. DataSize is a 32-bit
integer encoded into a 5-byte string.

This data format can contain all binary data except NUL byte.
Parsing might be faster than the old format.

Related: #202, #204

### CODE REVIEW

**Comment by Shougo** [comment]
:+1: 

I think you should check performance test.
benchmark.vim is already available.

**Comment by k-takata** [comment]
I use [vim-vimproc-benchmark](https://github.com/kamichidu/vim-vimproc-benchmark).

master:

```
        10	0.021800
       100	0.023600
       500	0.024300
      1000	0.025800
      5000	0.022800
     10000	0.023500
     50000	0.031200
    100000	0.038400
    500000	0.083900
   1000000	0.160400
```

This PR:

```
        10	0.022100
       100	0.021200
       500	0.025000
      1000	0.022100
      5000	0.024200
     10000	0.024400
     50000	0.025900
    100000	0.031500
    500000	0.077600
   1000000	0.145000
```

Oh, the current implementation seems already fast.

**Comment by Shougo** [comment]
OH...

**Comment by Shougo** [comment]
@k-takata The testing error is fixed.  Please rebase it.

**Comment by k-takata** [comment]
Rebased and squashed.

**Comment by Shougo** [comment]
@k-takata The tests are passed.  It is mergeable?

**Comment by k-takata** [comment]
I haven't tested this with VS2015.

**Comment by Shougo** [comment]
@k-takata Can you test it in VS2015?

**Comment by k-takata** [comment]
Maybe next weekend.

**Comment by Shougo** [comment]
OK.  I will wait.

**Comment by k-takata** [comment]
Note: If this PR is merged, version number should be updated.

**Comment by Shougo** [comment]
@k-takata I fixed the test error.  Please rebase it.

> Maybe next weekend.

Have you tested it in VS2015?

**Comment by k-takata** [comment]
> Have you tested it in VS2015?

Yes, it works.

**Comment by Shougo** [comment]
Thanks.  Merged.
I will change the version number.

**Comment by Shougo** [comment]
Version up to 9.0

**Pull request merged**
