### PR TITLE
Fix #202 change EOV to 0xFE

### LINKED ISSUE #202: when quit gvim  throw Exception
```
Error detected while processing function <SNR>188_finalize..<SNR>..188_vp_dlclose..<SNR>188_libcall: 
E605: Exception not caught : vimproc : vp_dlclose:['vp_stack_pop_mum:sscanf error']
E171: Missing :endif
```

above this is error message. what's wrong about me. 

this is the function throw exception,but i don't know why it throw?
```vimL
function! s:libcall(func, args) "{{{
  " End Of Value
  let EOV = "\xFF"
  let args = empty(a:args) ? '' : (join(reverse(copy(a:args)), EOV) . EOV)
  let stack_buf = libcall(g:vimproc#dll_path, a:func, args)
  let result = s:split(stack_buf, EOV)
  if get(result, -1, 'error') != ''
    if stack_buf[len(stack_buf) - 1] ==# EOV
      " Note: If &encoding equals "cp932" and output ends multibyte first byte,
      "       will fail split.
      return result
    endif
    let s:lasterr = result
    let msg = vimproc#util#iconv(string(result),
          \ vimproc#util#systemencoding(), &encoding)

    throw printf('vimproc: %s: %s', a:func, msg)
  endif
  return result[:-2]
endfunction"}}}
```

### PR DESCRIPTION
**Pull request by Shougo**
I created it for #202.
@k-takata @foxundermoon Please test it.

### CODE REVIEW

**Comment by k-takata** [comment]
Changing EOV value breaks binary compatibility. So, it might be a chance to change the data format.
IIRC, we cannot send EOV value itself. How about prepending data size before each data?

```
+------------+--------+------------+--------+-----+------------+--------+-----+
| datasize 1 | data 1 | datasize 2 | data 2 | ... | datasize N | data N | NUL | 
+------------+--------+------------+--------+-----+------------+--------+-----+
```

(Data size should be encoded so that it doesn't contain NUL bytes.)

**Comment by Shougo** [comment]
> Changing EOV value breaks binary compatibility. So, it might be a chance to change the data format.
IIRC, we cannot send EOV value itself. How about prepending data size before each data?

OK.  Can you implement it?

**Comment by k-takata** [comment]
Concept model of the new data encoder/decoder in Vim script:
https://gist.github.com/k-takata/37dd48139aff9dfdc4bd

**Comment by Shougo** [comment]
@k-takata Wow!  It is great.

**Comment by Shougo** [comment]
Closing by #206.

**Pull request closed without merging**
